sudo: required

language: generic

services:
  - docker

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install git-core --no-install-recommends --no-install-suggests -y
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

install:
  - docker build generator/ -t builder:latest
before_script:
  - docker run --rm -it -v `pwd`:/var/www/html builder:latest make
script:
  - git checkout -b `date +%Y-%m-%d`-ci
  - git add . *.sublime-snippet
  - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  - "git remote add origin-ci https://${GITHUB_TOKEN}@github.com/seregatte/AnsibleSnippets.git > /dev/null 2>&1"
  - git push --quiet --set-upstream origin-ci `date +%Y-%m-%d`-ci