sudo: required

language: generic

branches:
  only:
  - master
  - develop

services:
  - docker

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install git-core --no-install-recommends --no-install-suggests -y
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

install:
  - docker build generator/ -t builder:latest
  - export ANSIBLE_VERSION=`docker run --rm -it builder:latest ansible --version | head -1 | cut -d' ' -f2`
before_script:
  - docker run --rm -it -v `pwd`:/var/www/html builder:latest make
script:
  - export CI_BRANCH=`date +%Y-%m-%d`-ci
  - "git checkout -b  ${CI_BRANCH} || git checkout ${CI_BRANCH}"
  - git add . *.sublime-snippet
  - "git commit --message \"Travis build: ${TRAVIS_BUILD_NUMBER} for ${ANSIBLE_VERSION}\""
  - "git remote add origin-ci https://${GITHUB_TOKEN}@github.com/seregatte/AnsibleSnippets.git > /dev/null 2>&1"
  - git push --quiet --set-upstream origin-ci `date +%Y-%m-%d`-ci