sudo: required

language: generic

branches:
  only:
  - master
  - develop

services:
  - docker

jobs:
  include:
    - stage: "Build on CI"
      if: branch = develop
      script: .travis/develop.sh

    - stage: "Release a version"
      if: branch = master
      script: .travis/master.sh